### ISSUE TITLE
[Bug]: Not working after update to 2.6.0-115!

### ISSUE THREAD

**Issue by jvmahon** [t0bst4r/matterbridge-home-assistant-addon#115]
### What happened?

No longer starts up after update to 2.6.0-115.  Stuck at this screen:
![image](https://github.com/user-attachments/assets/3f73bd24-d55c-4423-a501-79d3db520e19)

I tried a full reset (deleting Matterbridge add-on as well as its storage folder from HomeAssistant).

### Your configuration

For configuration, I only use label-based includes:
![image](https://github.com/user-attachments/assets/87152c8a-d137-491c-ade0-49473edf03e9)

### Version

2.6.0-115 on latest HomeAssistant.

**Comment by jvmahon** [comment]
Noticed this error in the logs:
`````
[17:00:29.636] [Matterbridge] Matterbridge

qrPairingCode: MT:Y.K90AFN00UCYT1FC10

Manual pairing code: 12366138307

file:///usr/local/lib/node_modules/matterbridge/dist/matterbridge.js:2481
            this.log.debug(`WebSocketServer logger global callback: ${this.log.getGlobalCallback() ? 'active' : 'inactive'}`);
                                                                               ^

TypeError: this.log.getGlobalCallback is not a function
    at file:///usr/local/lib/node_modules/matterbridge/dist/matterbridge.js:2481:80

Node.js v18.20.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
`````

**Comment by t0bst4r** [comment]
Thank you for reporting. We already got the same issue in the main repo:
https://github.com/t0bst4r/matterbridge-home-assistant/issues/262

This is caused by a dependency of matterbridge, which is not under our control. 
unfortuantely we cannot fix it, but need to wait for this pull request to be merged and released:
https://github.com/Luligu/matterbridge/pull/98

**Comment by t0bst4r** [comment]
Interestingly i could not reproduce it with the addon, the docker image or even local development environment. Anyway i see other users to have that problem, too.
I created a bug fix with `2.6.1` which **hopefully** fixes it for you.
Could you please upgrade and give it a try. 😄

**Comment by acrelle** [comment]
> Interestingly i could not reproduce it with the addon, the docker image or even local development environment. Anyway i see other users to have that problem, too. I created a bug fix with `2.6.1` which **hopefully** fixes it for you. Could you please upgrade and give it a try. 😄

Thank you - I also had this issue, 2.6.1 has resolved, nice work.

**Comment by jvmahon** [comment]
Yes, it looks like that did it.
Closing the issue.
Thanks!
